# Generated by Django 5.0.7 on 2024-08-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_clothes_life_alter_album_name_product_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ibadah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('hari', models.CharField(max_length=255)),
                ('jam', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Komunitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('gembala_wilayah', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='product',
            name='clothes',
        ),
        migrations.RemoveField(
            model_name='main',
            name='community',
        ),
        migrations.RemoveField(
            model_name='main',
            name='product',
        ),
        migrations.CreateModel(
            name='Extensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('ibadah', models.ManyToManyField(to='home.ibadah')),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='LIFE',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
