# Generated by Django 5.0.7 on 2024-08-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ibadah_komunitas_remove_product_albums_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extensi',
            options={'verbose_name_plural': 'Extensi'},
        ),
        migrations.AlterModelOptions(
            name='ibadah',
            options={'verbose_name_plural': 'Ibadah'},
        ),
        migrations.AlterModelOptions(
            name='komunitas',
            options={'verbose_name_plural': 'Komunitas'},
        ),
        migrations.RenameField(
            model_name='ibadah',
            old_name='jam',
            new_name='nama_dan_jam',
        ),
        migrations.RemoveField(
            model_name='ibadah',
            name='nama',
        ),
    ]
