# Generated by Django 5.0.7 on 2024-08-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_extensi_options_alter_ibadah_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ibadah',
            old_name='hari',
            new_name='nama_dan_waktu',
        ),
        migrations.RemoveField(
            model_name='ibadah',
            name='nama_dan_jam',
        ),
    ]
