# Generated by Django 5.0.7 on 2024-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_hari_ibadah_nama_dan_waktu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ibadah',
            name='nama_dan_waktu',
        ),
        migrations.AddField(
            model_name='ibadah',
            name='hari',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='ibadah',
            name='jam_mulai',
            field=models.CharField(default='mulai', max_length=255),
        ),
        migrations.AddField(
            model_name='ibadah',
            name='jam_selesai',
            field=models.CharField(default='selesai', max_length=255),
        ),
        migrations.AddField(
            model_name='ibadah',
            name='nama',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
