# Generated by Django 5.0.7 on 2024-08-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_ibadah_nama_dan_waktu_ibadah_hari_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ibadah',
            name='nama',
        ),
        migrations.AddField(
            model_name='ibadah',
            name='ibadah_ke',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ibadah',
            name='hari',
            field=models.CharField(default='', max_length=255),
        ),
    ]
